import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import {
  BridgeWiseProvider,
  ThemeScript,
  TransactionProvider,
} from '@bridgewise/ui-components';
import './globals.css';

const customTheme = {
  primaryColor: '#22c55e',
  secondaryColor: '#0f172a',
  backgroundColor: '#020617',
  textColor: '#e5e7eb',
  borderRadius: '16px',
  fontFamily:
    'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  spacingUnit: '0.9rem',
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BridgeWiseProvider theme={customTheme} defaultMode="system">
          <TransactionProvider>{children}</TransactionProvider>
        </BridgeWiseProvider>
      </body>
    </html>
  );
}
